#!/usr/bin/env bash

: '

This file is part of library.file.sh project:
https://github.com/kz9676/library.file.sh

The MIT License (MIT)

Copyright (c) 2015 Kostya Zolotarov

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
of the Software, and to permit persons to whom the Software is furnished to do
so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

'

. directory_create
. directory_delete
. directory_copy
. directory_move
. directory_rename
. directory_find
. directory_assert

directory() {

    case "$1" in 

        # Create directory
        create)
        directory_create $2 
        ;;

        # Delete directory
        delete)
        directory_delete $2
        ;;

        # Copy directory
        copy)
        directory_copy $2 $3
        ;;

        # Move directory
        move)
        directory_move $2 $3 
        ;;

        # Rename directory
        rename)
        directory_rename $2 $3
        ;;

        # Find directory
        find)
        directory_find 
        ;;

        # Assert directory
        assert)
        directory_assert $2 $3
        ;;

        # Display library usage
        *)
        echo $"Usage: directory {create|delete|copy|move|rename|find|assert}"
        return 1
        ;;

    esac 

}

