#!/usr/bin/env bash

: '

This file is part of library.file.sh project:
https://github.com/kz9676/library.file.sh

The MIT License (MIT)

Copyright (c) 2015 Kostya Zolotarov

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
of the Software, and to permit persons to whom the Software is furnished to do
so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

'

. directory_assert_created
. directory_assert_deleted
. directory_assert_copied
. directory_assert_moved
. directory_assert_renamed
. directory_assert_found
. directory_assert_empty

directory_assert() {

    case "$1" in 

        # Assert directory created
        created)
        directory_assert_created $2 $3 
        ;;

        # Assert directory deleted
        deleted)
        directory_assert_deleted $2 $3
        ;;

        # Assert directory copied
        copied)
        directory_assert_copied $2 $3
        ;;

        # Assert directory moved
        moved)
        directory_assert_moved $2 $3 
        ;;

        # Assert directory renamed
        renamed)
        directory_assert_renamed $2 $3
        ;;

        # Assert directory found
        found)
        directory_assert_found $2 $3 
        ;;

        # Assert directory empty
        empty)
        directory_assert_empty $2 $3 
        ;;

        # Display library usage
        *)
        echo $"Usage: directory assert {created|deleted|copied|moved|renamed|found|empty}"
        return 1
        ;;

    esac 

}
