#!/usr/bin/env bash

: '

The MIT License (MIT)

Copyright (c) 2015-2020 Kostya Zolotarov

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
of the Software, and to permit persons to whom the Software is furnished to do
so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

'

. file_assert_created
. file_assert_deleted
. file_assert_copied
. file_assert_moved
. file_assert_written
. file_assert_read
. file_assert_renamed
. file_assert_found
. file_assert_empty

file_assert() {

    case "$1" in 

        # Assert file created
        created)
        file_assert_created $2 $3 
        ;;

        # Assert file deleted
        deleted)
        file_assert_deleted $2 $3
        ;;

        # Assert file copied
        copied)
        file_assert_copied $2 $3
        ;;

        # Assert file moved
        moved)
        file_assert_moved $2 $3 
        ;;

        # Assert file written
        written)
        file_assert_written 
        ;;

        # Assert file read
        read)
        file_assert_read 
        ;;

        # Assert file renamed
        renamed)
        file_assert_renamed $2 $3
        ;;

        # Assert file found
        found)
        file_assert_found $2 $3 
        ;;

        # Assert file empty
        empty)
        file_assert_empty $2 $3 
        ;;

        # Display library usage
        *)
        echo $"Usage: file assert {created|deleted|copied|moved|written|read|renamed|found|empty}"
        return 1
        ;;

    esac 

}

