#!/usr/bin/env bash

: '

The MIT License (MIT)

Copyright (c) 2015-2020 Kostya Zolotarov

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
of the Software, and to permit persons to whom the Software is furnished to do
so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

'

. file_create
. file_delete
. file_copy
. file_move
. file_write
. file_read
. file_rename
. file_find
. file_assert

file() {

    case "$1" in 

        # Create file
        create)
        file_create $2 
        ;;

        # Delete file
        delete)
        file_delete $2
        ;;

        # Copy file
        copy)
        file_copy $2 $3
        ;;

        # Move file
        move)
        file_move $2 $3 
        ;;

        # Write file
        write)
        file_write 
        ;;

        # Read file
        read)
        file_read 
        ;;

        # Rename file
        rename)
        file_rename $2 $3
        ;;

        # Find file
        find)
        file_find 
        ;;

        # Assert file
        assert)
        file_assert $2 $3
        ;;

        # Display library usage
        *)
        echo $"Usage: file {create|delete|copy|move|write|read|rename|find|assert}"
        ;;

    esac 

}

