#!/usr/bin/env bash 

: '

This file is part of srcmod project - command-line tool for automated setup and
maintenance of source code modules. 

The MIT License (MIT)

Copyright (c) 2015 Kostya Zolotarov

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
of the Software, and to permit persons to whom the Software is furnished to do
so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

'

# TODO - Implement sourcing for libraries

. ./configuration.*     # Build target's local configuration files
. library.log.sh        # https://github.com/kz9676/library.log.sh

## Executables

if [ ! -d $application_executables_path ];
then
    log warning "Application executables directory is not found - $application_executables_path"
    log information "Creating application executables directory - $application_executables_path"
    mkdir -p $application_executables_path
    if [ $? = 0 ];
    then 
        log success "Created application executables directory - $application_executables_path"
    else 
        log error "Failed to create application executables directory - $application_executables_path"
    fi 
fi 

for file in ${application_executable_files[@]};
do
    if [ -f $file ];
    then
        log information "Installing $file ..."
        cp -v ./$file $application_executables_path/${application_name}_$file
    fi 
done

for file in ${user_executable_files[@]};
do
    if [ -f $file ];
    then
        log information "Installing $file ..."
        cp -v ./$file $user_executables_path/${user_name}_$file
    fi 
done

## Libraries

if [ ! -d $application_libraries_path ];
then
    log warning "Application libraries directory is not found - $application_libraries_path"
    log information "Creating application libraries directory - $application_libraries_path"
    mkdir -p $application_libraries_path
    if [ $? = 0 ];
    then 
        log success "Created application libraries directory - $application_libraries_path"
    else 
        log error "Failed to create application libraries directory - $application_libraries_path"
    fi 
fi 

for file in ${application_library_files[@]};
do
    if [ -f $file ];
    then
        log information "Installing $file ..."
        cp -v ./$file $application_libraries_path/$file 
    fi 
done

for file in ${user_library_files[@]};
do
    if [ -f $file ];
    then
        log information "Installing $file ..."
        cp -v ./$file $user_libraries_path/$file 
    fi 
done

## Configurations

if [ ! -d $application_configurations_path ];
then
    log warning "Application configurations directory is not found - $application_configurations_path"
    log information "Creating application configurations directory - $application_configurations_path"
    mkdir -p $application_configurations_path
    if [ $? = 0 ];
    then 
        log success "Created application configurations directory - $application_configurations_path"
    else 
        log error "Failed to create application configurations directory - $application_configurations_path"
    fi 
fi 

for file in ${application_configuration_files[@]};
do
    if [ -f $file ];
    then
        log information "Installing $file ..."
        cp -v ./$file $application_configurations_path/$file 
        echo ". $HOME/.$application_name" >> $application_configurations_path/$file
    fi 
done

for file in ${user_configuration_files[@]};
do
    if [ -f $file ];
    then
        log information "Installing $file ..."
        cp -v ./$file "$user_configurations_path"."$application_name"
    fi 
done

## Templates

if [ ! -d $application_templates_path ];
then
    log warning "Application templates directory is not found - $application_templates_path"
    log information "Creating application templates directory - $application_templates_path"
    mkdir -p $application_templates_path
    if [ $? = 0 ];
    then 
        log success "Created application templates directory - $application_templates_path"
    else 
        log error "Failed to create application templates directory - $application_templates_path"
    fi 
fi 

for file in ${application_template_files[@]};
do
    if [ -f $file ];
    then
        log information "Installing $file ..."
        cp -v ./$file $application_templates_path/$file
    fi 
done

for file in ${user_template_files[@]};
do
    if [ -f $file ];
    then
        log information "Installing $file ..."
        cp -v ./$file $user_templates_path/$file
    fi 
done

