#!/usr/bin/env bash 

: '

This file is part of https://github.com/kz9676/bash-project - command-line tool
for automated setup and maintenance of Bash projects and source code. 

The MIT License (MIT)

Copyright (c) 2015 Kostya Zolotarov

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
of the Software, and to permit persons to whom the Software is furnished to do
so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

'

. configuration.project
. log
. file
. version

version_file_name=VERSION
version_file_path=. 
version_file=$version_file_path/$version_file_name

project_version() {

    if [ -f $version_file ];
    then
        # If ./VERSION file is empty, initialize it with '0.0.0.0'
        file assert empty "$version_file"
        if [ $? == 0 ];
        then
            version_number='0.0.0.0'
            log information "Initializing $version_file with $version_number ..."
            printf "$version_number" > "$version_file"
        fi 
        log information "Reading version ..."
        version="$(<$version_file)"
        if [ -n "$version" ];
        then
            log information "Incrementing version $version ..."
            version_increment $version $version_file 
        else 
            log error "Failed to read previous version."
            exit 1
        fi 
    else 
        log error "Failed to increment version. $version_file not found."
        exit 1
    fi

}
