#!/usr/bin/env bash 

: '

This file is part of https://github.com/kz9676/bash-project - command-line tool
for automated setup and maintenance of Bash projects and source code. 

The MIT License (MIT)

Copyright (c) 2015 Kostya Zolotarov

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
of the Software, and to permit persons to whom the Software is furnished to do
so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

'

. ./configuration.project
. ./log

output_file_name=README
output_file_path=. 
output_file=$output_file_path/$output_file_name

project_readme() {

    > $output_file
    log information "Updating $output_file ..."
    for source_module_file in ${source_module_descriptors[@]};
    do
        if [ -s $source_module_file ];
        then
            source_module_file_text="$(<$source_module_file)"
            log information "Writing section title for $source_module_file ..."
            let counter++ 
            numbered_heading "$counter" "$source_module_file" | xargs printf "%s\n\n" >> $output_file
            log information "Writing contents of $source_module_file ..."
            printf "$source_module_file_text\n\n" >> $output_file 
        fi 
    done

}
