#!/usr/bin/env bash

: '

This file is part of srcmod project - command-line tool for automated setup and
maintenance of source code modules. 

The MIT License (MIT)

Copyright (c) 2015 Kostya Zolotarov

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
of the Software, and to permit persons to whom the Software is furnished to do
so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

'

# TODO - Move message formatting to an external library

parent_directory_name=${PWD##*/}
source_module_name=$parent_directory_name
info="~~> INFO:" 
warning="~~> WARNING:" 
error="~~> ERROR:" 
ok="~~> OK:" 

# Source module descriptors
source_module_files=(
    AUTHORS
    BACKGROUND
    BUILD
    CHANGELOG
    DEFECTS
    DEPENDENCIES
    DESCRIPTION
    DESIGN
    FILES
    INSTALL
    LICENSE
    REQUIREMENTS
    SOURCES
    TASKS
    TEST
    VERSION
)

printf "$info Initializing $source_module_name source module...\n" >&2
for source_module_file in ${source_module_files[@]};
do
   printf "$info Creating $source_module_file ...\n" >&2
   if [ ! -f $source_module_file ];
   then
       touch $source_module_file 
   fi 
   touch $source_module_file
done
